title: Zijian Jiang 
logo: "/images/IMG_4924.JPG?raw=true" #  photo 
description: > 
  In school Master student at University of Waterloo
  <br><br>
  Faculty of Environment, research interest lays on computer vision, deep learning
  <br><br>
  Basketball Player 
  <br><br>
  <p <a href="www.linkedin.com/in/zijian-jiang-9704/"> My LinkedIn Profile </a> </p>
  
theme: jekyll-theme-minimal
