title: Zijian Jiang 
logo: "/images/IMG_4924.JPG?raw=true" #  photo 
description: > 
  Master of Environmental Study, Geography, University of Waterloo
  <br><br>
  Research Interest: Data analysis, Deep-learning; Artificial intelligence; Land-cover classification
  <br><br>
  Working at <a href="https://uwaterloo.ca/geospatial-sensing/"> Geospatial Sensing and Data Intelligence Lab</a>
  <br><br>
  Basketball Player 
  <br><br>
  <a href="www.linkedin.com/in/zijian-jiang-9704/"> My LinkedIn Profile</a>
  <br><br>
  My CV
  
theme: jekyll-theme-minimal
